version: '3.9'

services:
  api:
    build: './api'
    container_name: api
    ports:
      - '3001:3001'
    networks:
      - rede

  front:
    build: './front'
    container_name: front
    ports:
      - '3000:3000'
    networks:
      - rede

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - rede

volumes:
  mongo-data:

networks:
  rede:
    driver: bridge
